stages:
  - build
  - test

build_job:
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  script:
    - echo "Building Docker images..."
    - docker-compose build

test_job:
  stage: test
  script:
    - echo "Starting containers..."
    - docker-compose up -d
    - docker-compose ps
    - echo "Waiting for Flask app to be ready..."
    - sleep 10
    - docker-compose exec flask pytest