stages:
  - build
  - test

services:
  - docker:dind

before_script:
  - echo "Preparing environment..."
  - docker info
  - docker-compose --version

build_job:
  stage: build
  script:
    - echo "Building Docker images..."
    - docker-compose build

test_job:
  stage: test
  script:
    - echo "Starting containers..."
    - docker-compose up -d
    - docker-compose ps
    - echo "Waiting for Flask app to be ready..."
    - sleep 10
    - docker-compose exec flask pytest